apiVersion: v1
kind: Secret
metadata:
    name: teleport-kube-agent-join-token
    namespace: teleport
stringData:
    auth-token: ENC[AES256_GCM,data:b/5b/L8O+YiFQeE+eqbjc9bxShry3zSNkD7MB/aX370=,iv:NPI6xiSqpOcpaYBWOzzGlqNR3pmh6sHHxxkBRhv4LsQ=,tag:0b8LyxPK35Pe6YDh6DcpBA==,type:str]
sops:
    age:
        - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbFFZVE12UXcwRGc4S2g2
            MVBBSjNlcjVYV3NGM0Y4UThaMzZnazFGT0dzCkoxb0pKd1poaFdqamErbVhWaXZU
            eUFRS0ZDaTBNREliZHRaSzRaRmNFY2cKLS0tIFJ4cEViT08yaHNHbEFLUG00Z0tN
            NGY2MktVUjgreEs3U2krcm9GcHJucG8KKabMTwuLzuk/XLLay9n7E85TyUonekf1
            N8fRw6JaFniFjC1/k1JLFRAN37kRR4rLlFuesPo0kkLPgoBSUjgNLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T10:26:07Z"
    mac: ENC[AES256_GCM,data:8WOq4OTbbwpJCBZS1lrPcsfabZlqdy2rygEvccE3Zwu9SJUfBvOLJe/IM0eA6cmhGWUhjLSj8UzttFl8m6yzAbxeIli4+EqHeTcKZQiKcVrNq2v76zWfSpIgbG6GiX+8xB4JW+SGeSxQ4KlPn0O/2XXBJW93KwY6cI1caGComxg=,iv:GR3Twt5ZNxJNnm3dRLen+8DG8EuGOlggXjaM3VZ/gKs=,tag:6V+CujwLS1rzifE+fczPAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
