apiVersion: v1
kind: Namespace
metadata:
  name: etherpad
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        volumeMounts:
        - name: postgres-mount
          mountPath: /var/lib/postgres/data
        env:
        - name: POSTGRES_USER
          value: etherpad
        - name: POSTGRES_PASSWORD
          value: daprehte
        - name: POSTGRES_DB
          value: etherpad
      volumes:
        - name: postgres-mount
          persistentVolumeClaim:
            claimName: postgres-storage

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: etherpad
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad-deployment
  namespace: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
      - name: etherpad
        image: etherpad/etherpad
        ports:
        - containerPort: 9001
        env:
        - name: TITLE
          value: pad
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: etherpad
        - name: DB_USER
          value: etherpad
        - name: DB_PASS
          value: daprehte
        - name: ADMIN_PASSWORD
          value: ""
        - name: SKIN_VARIANTS
          value: "dark-toolbar super-dark-background dark-editor"
          #"skinVariants": "dark-toolbar super-dark-background dark-editor",
---
apiVersion: v1
kind: Service
metadata:
  name: etherpad-service
  namespace: etherpad
spec:
  selector:
    app: etherpad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: etherpad
  namespace: etherpad
spec:
  tls:
  - hosts:
    - etherpad.phonkd.net
    secretName: nginx-tls-secret
  ingressClassName: nginx
  rules:
  - host: etherpad.phonkd.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: etherpad-service
            port:
              number: 80
