# cilium values
apiVersion: v1
data:
  cilium-values.yaml: |
    ipam:
      mode: kubernetes
    kubeProxyReplacement: false
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCilumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
---
# ClusterResourceSet to automatically install Cilium
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cilium-crs
  namespace: kube-system
spec:
  clusterSelector:
    matchLabels:
      cni: cilium
  resources:
    - kind: ConfigMap
      name: cilium-install
  strategy: Reconcile
---
# ConfigMap with SA + RBAC + Job that installs Cilium via Helm
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-install
  namespace: kube-system
data:
  install-cilium.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: cilium-installer
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: cilium-installer-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
      - kind: ServiceAccount
        name: cilium-installer
        namespace: kube-system
    ---
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: install-cilium
      namespace: kube-system
    spec:
      template:
        spec:
          volumes:
            - name: cilium-values
              configMap:
                name: cilium-config
                items:
                  - key: cilium-values.yaml
          serviceAccountName: cilium-installer
          restartPolicy: OnFailure
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
            - effect: NoSchedule
              key: node.kubernetes.io/not-ready
          tolerations:
            - effect: NoSchedule
              operator: Exists
          containers:
            - name: install-cilium
              volumeMounts:
                - name: cilium-values
                  mountPath: /cilium-values.yaml
                  subPath: cilium-values.yaml
              image: alpine/helm:3.13.0
              env:
                - name: KUBERNETES_SERVICE_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: KUBERNETES_SERVICE_PORT
                  value: "6443"
              command:
                - /bin/sh
                - -c
                - |
                  helm repo add cilium https://helm.cilium.io
                  helm repo update
                  helm upgrade --install cilium cilium/cilium \
                    --namespace kube-system \
                    --create-namespace \
                    --set k8sServiceHost=${KUBERNETES_SERVICE_HOST} \
                    --set k8sServicePort=${KUBERNETES_SERVICE_PORT} \
                    --values /cilium-values.yaml
