apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: mc20
  labels:
    app: mc20
  name: mc20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc20
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mc20
    spec:
      containers:
      - image: phonkd/minecraft:v1.21
        name: mcsrv
        env:
         - name: max_memory
           value: 8192M
        ports:
          - name: mcmain
            containerPort: 25565
          - name: mcrcon
            containerPort: 25575
        resources:
          requests:
            memory: "8Gi"
          limits:
            memory: "12Gi"
        volumeMounts:
          - name: srvdata
            mountPath: /mc
      volumes:
        - name: srvdata
          persistentVolumeClaim:
            claimName: minecraft-pvc
