apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mc20
  name: mc20
  namespace: mc20
spec:
  ports:
  - name: "25575"
    port: 25575
    protocol: TCP
    targetPort: 25575
  selector:
    app: mc20
  type: NodePort
status:
  loadBalancer: {}
