# Talos-based cluster using CAPI with Proxmox
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: phonkd-test-01
  namespace: kube-system
  labels:
    cni: cilium
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: phonkd-test-01-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: phonkd-test-01
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: phonkd-test-01
  namespace: kube-system
spec:
  allowedNodes:
    - oldblac
  controlPlaneEndpoint:
    host: 192.168.1.209
    port: 6443
  dnsServers:
    - 8.8.8.8
    - 8.8.4.4
  ipv4Config:
    addresses:
      - 192.168.1.210-192.168.1.225
    gateway: 192.168.1.1
    prefix: 24
  schedulerHints:
    memoryAdjustment: 0
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: phonkd-test-01-control-plane
  namespace: kube-system
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.8
      configPatches:
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: external
            rotate-server-certificates: "true"
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
            manifests:
              - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
              - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
        - op: add
          path: /machine/features/kubernetesTalosAPIAccess
          value:
            enabled: true
            allowedRoles:
              - os:reader
            allowedKubernetesNamespaces:
              - kube-system
        # - op: add
        #   path: /machine/network
        #   value:
        #     interfaces:
        #       - interface: eth0
        #         dhcp: true
        #         vip:
        #           ip: 192.168.1.209

        #     nameservers:
        #       - 8.8.8.8
        #       - 8.8.4.4
        - op: add
          path: /machine/time
          value:
            disabled: false
            servers:
              - time.cloudflare.com
        - op: add
          path: /cluster/network/cni
          value:
            name: none
        - op: add
          path: /cluster/proxy
          value:
            disabled: true
        # - op: add
        #   path: /cluster/apiServer/extraArgs
        #   value:
        #     cloud-provider: external
        # - op: add add when installed ccm
        #   path: /cluster/controllerManager/extraArgs
        #   value:
        #     cloud-provider: external
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: phonkd-test-01-control-plane
    namespace: kube-system
  replicas: 1
  version: v1.31.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: phonkd-test-01-control-plane
  namespace: kube-system
spec:
  template:
    spec:
      checks:
        skipCloudInitStatus: true
      metadataSettings:
        providerIDInjection: true
      vmIDRange:
        start: 800
        end: 899
      disks:
        bootVolume:
          disk: virtio0
          sizeGb: 100
      format: qcow2
      full: true
      memoryMiB: 16384
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 1
      numSockets: 1
      sourceNode: oldblac
      templateID: 210
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: phonkd-test-01-workers
  namespace: kube-system
spec:
  clusterName: phonkd-test-01
  replicas: 5
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: phonkd-test-01
      cluster.x-k8s.io/deployment-name: phonkd-test-01-workers
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: phonkd-test-01
        cluster.x-k8s.io/deployment-name: phonkd-test-01-workers
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: phonkd-test-01-worker
      clusterName: phonkd-test-01
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: phonkd-test-01-worker
      version: v1.31.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: phonkd-test-01-worker
  namespace: kube-system
spec:
  template:
    spec:
      checks:
        skipCloudInitStatus: true
      metadataSettings:
        providerIDInjection: true
      vmIDRange:
        start: 900
        end: 999
      disks:
        bootVolume:
          disk: virtio0
          sizeGb: 80
      format: qcow2
      full: true
      memoryMiB: 16384
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 4
      numSockets: 1
      sourceNode: oldblac
      templateID: 210
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: phonkd-test-01-worker
  namespace: kube-system
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.8
      configPatches:
        - op: add
          path: /machine/network
          value:
            interfaces:
              - interface: eth0
                dhcp: true
            nameservers:
              - 8.8.8.8
              - 8.8.4.4
        - op: add
          path: /machine/time
          value:
            disabled: false
            servers:
              - time.cloudflare.com
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: external
            rotate-server-certificates: "true"
