apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: phonkd-dev-project
  namespace: argocd
spec:
  sourceNamespaces:
    - phonkd-dev
  sourceRepos:
    - https://github.com/phonkd/inventory
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
