apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pve-csi
  namespace: argocd
spec:
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: ghcr.io/sergelogvinov/charts
    targetRevision: 0.3.5
    chart: proxmox-csi-plugin
    helm:
      valuesObject:
        existingConfigSecret: csipveconfig
        storageClass:
          - name: proxmox-data-xfs
            storage: nvme-zfs
            cache: writeback
            ssd: "true"
            fstype: ext4
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
