apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pve-csi
spec:
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: ghcr.io/sergelogvinov/charts
    targetRevision: 0.3.5
    chart: proxmox-csi-plugin
    helm:
      valuesObject:
        existingConfigSecret: csipveconfig
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
