clusters:
  - insecure: true
    region: idk
    token_id: kubernetes-csi@pve!csi
    token_secret: dontputquoationmarksaroundthis
    url: https://192.168.1.46:8006/api2/json
features:
  provider: default
