config:
  clusters:
    - url: https://kek:8006/api2/json
      insecure: true
      token_id: "kubernetes-csi@pve!csi"
      token_secret: ""
      region: idk
# Define the storage classes
storageClass:
  - name: proxmox-data-xfs
    storage: data
    reclaimPolicy: Delete
    fstype: xfs
    # Define the storage class as default
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
