---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csipveconfig
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgA6a+cwiEGlDBu/xwZF0AP+nPVWT9rkfmCGDnnJgHtZLNMUkcG3JFn1CX6cyrP4eYo6LN/VHK0d+QKsKzKH4TFJo0iDZe1vAaGhUww9xzy+TDgI/OhWDFYNOKvDvoVuznxtb519NwVSPBDdxThhI7W5WGD8U7lpIzf96YNcdRAAoTreBF8kXyEtO1hzCZd2W+b5yUf1Ar29B+ZvJr9HfoXNLTYMwO32UlcbIDS7u4XTNxsf3f9dpeO3LpLXNlwubGCGs2rCFFCpuqoCR+JQWkY2yJuQjkZO0Q4H8bXMZL51yYdxcHg3XiFW9kva1AZbGUx70PImowsapwow2l2K3mLj8nHYpXZ9F9Gn4GnHWv+lT92rDW+lb+nHH3siC5gANj6zyimON8nY6JiRdBzpkndfYrFL6WY3rudgKkyi7JMuqRLgFK38fz83EeZH6jF9/816yplTe2hj/TOWdeJZlx06CNsHg3eQVFeyCd2hz9iLPaDvp2tevz2/pc5IvLbMocDptEbxTV+VVGM+KRcv/Ca/SaWsYP6HiP0GtLKTVW4b9rlAZEjDaUiNAtNGwgBg3dcTprMIU9ySemVQQWS1F7TOsDZSt95Iy5xsl2ZkDfSG9j6eZSYfsgqNF33NV4symLccshSZjFz6lavSWl9qDjohN73rjDg8w5n7kbQFiPLE095Aq4E1ZkBpEDB5T/PGOhGWoJoufUcnbR2mkU7JwLuimcI8SaC26fC8L+mN4LOXvelr1nV4nJl082ieWOkx7NGX8fzKKWTZ2xW3K4/bk5lt2VBoe4tivObypd0k9G7mrjK/lObheIfa8QGG6sp4LZpzVrjkYIcAmOIXL8UvHdPSusaV0dxhMLO6liKXWx6k59rAfkfUIw3rbohxGVqyRV1svDi/lynWAxr/FMbhFtaye9Zm7/sia3tjZDzgkN6xIMuM1qcBjgnf5yp0eK7V9xMQiiVYs3iwbtKVekjAsZPqqKnCDOkRldKi04I3X2ct4mmUxJzgSZP7ztRGfxsYM2gzzwc9QPepU7+u9vXMj6mKQBCCxYUUIalHCqO0FA6/LtTCcP3O/CLDgyuaBbnSBi3kz5OGPvAzd7lkzmui64/81KcNReiqkefnv8mq0CgHGRdpL6/VazOSC40lABGsS8ocspyoGHwWlg0lQWhU6L2IQtbWrv4xOI287cFdQeHmuRNX2XzOa5hLd5n8YONrW51t0lZrHVfsqWo4WvV+3CF9WYJzb1jEXsvDFBgD5tMhcYZZTLJEdeYAAHv5vPJagL4taKtRC0s/9wobbALiS+HapJbG1ns=
  template:
    metadata:
      name: csipveconfig
      namespace: csi-proxmox
