apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csipveconfig
  namespace: argocd
spec:
  encryptedData:
    config.yaml: AgAHOeWelUYK0uCvKRVVgiPLlVQYEwbzh+4K2O0Q/JWqCqUSxKUGEQt/DTcVS6eU8jy3ZKlYgCJWnzj/GnUuyGtdYmZq4pjvEsqnieLHzP1UxWtfV4XtIbTmcdBQgepUEwp5zYchHMlOliiQiDooUaBhX1gXD1P0ARn4lxCvHJiNzFkEpxkRDwPBMyb1pn8I5X4T3G1xckilQjE0dbCXeKca4lz3QbzOQIfk2DGDXYyYhA5b7GuPFq25RLH3VGg8SQYl6JaJ0RIx7sMOSrG148nZiB8HNgHP2jtCQnyaD5XCOkDdQjPPOCYttinCqqeXHn5H1oWPLZxiBa5PcTQ8JzehJEJgMwRcui/oBsD/0M7YeJ24UiJ3Kh3zp0y6b3K4T9G/15FgQrCn8CfoReLuFhZK0cNKdgZYZogxYSHNEpy6/TMdzUQXcd1psY2XxNfVJJpaFVmAWz8wzf5ufMiQeJIim2NTDMDlMVp2M5f8btzKg7OCpc0bwt4ZHAODN9EsKJbnSBYoAj7B1zDRoeUV04VieK+5v3VkHERprxHtVu3nDb2rg3aBH4QN03Fl+1wvGO0Yf8kqVrvrU0zXK82hgrGuUiVKHfzGmtEvsZdWrqn1iAgCDL5yaG6waL1+OHbMwr/T93VxCkHMN9hnxXADJ4GEk4Kf07czqyswrRkrIhkSOmbDUMzKAOo253AZUVRXTTGJNBoW3gtl5LNQlE6mYXtE0740nMYhQubOroEG2yj4gbw2mHZ5pl33T2q7YIXN00qKgZqUCnsJmQMejT5gLN7u84LMHsHwSPhSjDt3KDJkzkFob2GgkODFy5uhZoPAdwtRFrOXlgUDCMY+kH5uIVBNnU+HcMqYU7QvTS2eCYH+fIbaAzgQ19oIf3WHQazUe3a/Z+RU6xVCFvd8fXhc8BFrh94Lw/94Sux3Vm+dGtFpChUkE2yllxnBH6SH495y9p5C17t6ERSyNeO2LdReaIgVXbi2tV14uKFMf26tvAFo8MQPBUuIEqvkrJwXL7wTkUMCRHpOIDbMLLhIX0KhHywdxSAxDalkE/zIbISxALlkmJjkuRptXK0AWykcucjPZtIq5QGI8DwKdI5UrdtttM2ALJXq+SMKI3D0XZIfJlQjplgMj2GQtMAie4rKd6DScefWxWLXjMkLF1XlN+i8SqyOyT1G3rEDdALXozkj4mLpcUd8CrYfzwHrn0Cat9L6cr2qczj5/I97yeDk3XaFCFubfmDKlrIGWlH5hy8yp+3z6yz7CbdoZQDtvXgqguFHFwFQqvz/Iinlsjrfd6FoJ66DbtuGGw9uQ0rIBQ==
  template:
    metadata:
      creationTimestamp: null
      name: csipveconfig
      namespace: argocd
