apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    name: ""
    namespace: ""
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.8
    chart: metallb
  project: default
  syncPolicy:
    automated:
      self-Heal: true
      prune: true
