redis-cluster:
  enabled: false
postgresql:
  enabled: true
  image:
    tag: 15.5.0
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  size: 50Gi

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    server:
      SSH_DOMAIN: giteassh.phonkd.net
      SSH_PORT: 30123
      USE_COMPAT_SSH_URI: true
    service:
      REGISTER_MANUAL_CONFIRM: true
    ui:
      THEMES: catppuccin-latte-rosewater,catppuccin-latte-flamingo,catppuccin-latte-pink,catppuccin-latte-mauve,catppuccin-latte-red,catppuccin-latte-maroon,catppuccin-latte-peach,catppuccin-latte-yellow,catppuccin-latte-green,catppuccin-latte-teal,catppuccin-latte-sky,catppuccin-latte-sapphire,catppuccin-latte-blue,catppuccin-latte-lavender,catppuccin-frappe-rosewater,catppuccin-frappe-flamingo,catppuccin-frappe-pink,catppuccin-frappe-mauve,catppuccin-frappe-red,catppuccin-frappe-maroon,catppuccin-frappe-peach,catppuccin-frappe-yellow,catppuccin-frappe-green,catppuccin-frappe-teal,catppuccin-frappe-sky,catppuccin-frappe-sapphire,catppuccin-frappe-blue,catppuccin-frappe-lavender,catppuccin-macchiato-rosewater,catppuccin-macchiato-flamingo,catppuccin-macchiato-pink,catppuccin-macchiato-mauve,catppuccin-macchiato-red,catppuccin-macchiato-maroon,catppuccin-macchiato-peach,catppuccin-macchiato-yellow,catppuccin-macchiato-green,catppuccin-macchiato-teal,catppuccin-macchiato-sky,catppuccin-macchiato-sapphire,catppuccin-macchiato-blue,catppuccin-macchiato-lavender,catppuccin-mocha-rosewater,catppuccin-mocha-flamingo,catppuccin-mocha-pink,catppuccin-mocha-mauve,catppuccin-mocha-red,catppuccin-mocha-maroon,catppuccin-mocha-peach,catppuccin-mocha-yellow,catppuccin-mocha-green,catppuccin-mocha-teal,catppuccin-mocha-sky,catppuccin-mocha-sapphire,catppuccin-mocha-blue,catppuccin-mocha-lavender
    
    #ui:
     # DEFAULT_THEME: theme-edge-dark
      #THEMES: theme-edge-auto,theme-edge-dark,theme-edge-light,theme-everforest-auto,everforest-dark,theme-everforest-light,theme-gruvbox-auto,theme-gruvbox-dark,theme-gruvbox-light,theme-gruvbox-material-auto,theme-gruvbox-material-dark,theme-gruvbox-material-light,theme-nord,theme-palenight,theme-soft-era,theme-sonokai-andromeda,theme-sonokai-atlantis,theme-sonokai,theme-sonokai-espresso,theme-sonokai-maia,theme-sonokai-shusia
  # additionalConfigFromEnvs:
  #   - name: GITEA__UI__THEMES
  #     value: theme-edge-auto,theme-edge-dark,theme-edge-light,theme-everforest-auto,theme-everforest-dark,theme-everforest-light,theme-gruvbox-auto,theme-gruvbox-dark,theme-gruvbox-light,theme-gruvbox-material-auto,theme-gruvbox-material-dark,theme-gruvbox-material-light,theme-nord,theme-palenight,theme-soft-era,theme-sonokai-andromeda,theme-sonokai-atlantis,theme-sonokai,theme-sonokai-espresso,theme-sonokai-maia,theme-sonokai-shusia

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
      - gitea.phonkd.net
      secretName: nginx-tls-secret
  hosts:
    - host: gitea.phonkd.net
      paths:
        - path: /
          pathType: Prefix

service:
  ssh:
    type: LoadBalancer
    #clusterIP: None
    loadBalancerIP: 10.0.0.161
    port: 30123
    annotations:
      metallb.universe.tf/allow-shared-ip: "sharedip-key-10.0.0.161"

extraVolumes:
  - name: gitea-themes
    secret:
      secretName: gitea-themes

extraVolumeMounts:
  - name: gitea-themes
    readOnly: true
    mountPath: "/data/gitea/public/assets/css"
