apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
spec:
  destination:
    name: ""
    namespace: paperless
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://fmjstudios.github.io/helm
    targetRevision: 0.2.3
    chart: paperless-ngx
    helm:
      values: |
        paperless:
          data:
            pvc:
              storageClass: longhorn
          primary:
            persistence:
              storageClass: longhorn
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
