apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ingresscontroller-ext.yaml
  - ./letsencrypt-cert-manager/app.yaml
  - ./letsencrypt-cert-manager/issuer.yaml
  - ./letsencrypt-cert-manager/cloudflare-api-token-secret.yaml
