apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-services-nix
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: nix/crap
    repoURL: https://github.com/phonkd/k8s-services.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
