apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: kubemox-creds
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./wamluck-kubemox.enc.yaml
