apiVersion: v1
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: csi-proxmox
stringData:
    config.yaml: ENC[AES256_GCM,data:Qx5IkK54G4JBrfeHNbXe/Cjx5HXjbZM8lkh4BE4TKN1VZ41Jt8O8TVuPhI12YzfAjOa/DrPosHXfEPc6QEsGEgDf0pQklojTVMVKoRPOORJkWt0PdiVLphtXvZ2iVzVg0MKoIXQyRGcQTMffG0znB8ffcZJr7lQnQT+itOG4+EDhtl8Xs4iQCyorDDXNKnqafoMBxEswopKG5nZDTbN261+jmYLqnmsF1HeHl3SyRyyku8y1P/Dzi6rDP3qwTaCbDMo=,iv:OcAh+YfBvaZEsx8fAdmECz/ugLJ5t2x5RToqWXEmOak=,tag:e8jE73k58CreyCJGl7gCrg==,type:str]
# config.yaml:
#         clusters:
#             # List of Proxmox clusters
#             - url: https://.../api2/json
#               # Skip the certificate verification, if needed
#               insecure: false
#               # Proxmox api token
#               token_id: kubernetes-csi@pve!csi
#               token_secret:
#               # Region name, which is cluster name
#               region: Region-1
sops:
    age:
        - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcjE3QUxGeXVWNWh6UVM0
            RWFKU3pQc08reURaWEo3ai9hcWN0UmhvK1UwClJ6QU5vc0tTUUtHZ1RBNUNzcCti
            b3NobGFRWHFVa1VTTGRpTmpva2dVRjAKLS0tIEpnK0t4UCtoL3I4dGJzbmZyODJY
            UWg1MDVJdGxCcG1OU3BKYkt2M1hvdEEKlPm1WVcHxJynWfm+/Gn9jkgbNlOiwSmN
            IYidwzjwnx3OBceU6hpi/iKYusCVbeGs77gqVvKrZhkIR7QVInMvZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:17:36Z"
    mac: ENC[AES256_GCM,data:fGNFp6ljDcmeFQ50THg5WpiT8XLP1RtvZIWmomFQETBi2wsA8Um5iD3tljVY5oryOF/GXdJ0xWAvs5EnkDIghrDfz/fOGHzgUXdxLaJkeSeK4v9cjZXSkoGT/7bv3+aokAS/oBITJHkzR/li/xm3t32CTj6v8b6Rzie4etlN6Qg=,iv:XGMyiAur4EpUTKp0Z7d8zrg3246f1afATRfGJRoHAJo=,tag:tEbig06GFjlZC5KOFe5tgQ==,type:str]
    encrypted_regex: ^(config\.yaml)$
    version: 3.12.2
