apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.16.1
    chart: sealed-secrets
  sources: []
  project: default
  syncPolicy:
    automated: null
