apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ddns
  name: ddns
spec:
---
# WARNING, this is where you create the secret:
# `kubectl create secret generic -n ddns --from-file editme.txt infomaniak-ddns-credentials`

apiVersion: batch/v1
kind: CronJob
metadata:
  generation: 1
  name: ddns-updater-cron
  namespace: ddns
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: ddns-updater-cron
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: phonkd/infomaniak-ddns-updater:v0.6
            name: ddns-updater-cron
            envFrom:
            - secretRef:
               name: infomaniak-ddns-credentials
            env:
            - name: USER
              value: "changeme"
            - name: PASS
              value: "changeme"
            - name: DOMAIN
              value: "phonkd.net"
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 10
  suspend: false
---
