{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|ramfs\",mountpoint!~\"/mnt/Shares|/nix/store\"} /node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|ramfs\",mountpoint!~\"/mnt/Shares|/nix/store\"})) * 100",
     "legendFormat": "{{hostname}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "mystrom_power", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}