apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: teleport-kube-agent-join-token
  namespace: teleport-sel
spec:
  encryptedData:
    auth-token: AgCAklwrhncoZNelZJTYzSY+aD/9jNJb6VvQ3gLmiedsyf7Itbb92/tF/C0AUwwCT6J+dHDRMyDRpQYRWdTZioX1utI2/e94KDUBEdH8khgA4nVx7McXrzQgsx2LNrqqMHTBVsys0mJCGWaB3cqvXxqOY0xGNBUOISHaCRNK4eN5GR8qREaZT3q9NtDKyOMH7mdswEKVxa8Q0mIlfeKxvLwXmUMuQNKs2C/xbnYDenVhrsfE+V+KvlRHFoWM7ESllECsLfHKo6sVt1OPusVBvkQxPJ+oCj5CJqbN0J8z57rKCT7pAqDyLj605CGeusUBe1vZF7WNZLPZ1j8F5612hkYJdw0O+ic1S0qmdZg7X+9Fz6QKEQcZNsRTt2nywbNhLzy7LwHSbWjPaC3qGbaBDrPoi5L54CXPIIWaHORVU+pZaxjvOpdX1zg8VIZgdj/Gau4Yk/rcqRbdm/CO65fATtLQs7ikRkKZDLABcnEkES68Iv3QGqQB+hEobDIfH8kTlbc7Qh4QIdnzzXJuSicIIkfoZ3r8yzUFDaKxNhhP4eBfJcABVSdncx4yNp7+762As4oULCoOZrDr38fgLn/OIMs34eIfUV7HPpV1Jj07n1kAwqXTfrJvslK2J/GNwLS0Mmn0k0LchO4oC6cEi47ADQO6Y5087a+zBQw16hGVBZxjQJbGjQNStV8mZiWPPV03b85m8GRzGRf2S4g6dZL1/3gpcbD4k0GeOM6BoEZLzgVmZQ==
  template:
    metadata:
      name: teleport-kube-agent-join-token
      namespace: teleport-sel
