apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: proxmox-csi-plugin
    repo: oci://ghcr.io/sergelogvinov/charts
    version: 0.4.0
    releaseName: proxmox-csi-plugin
    namespace: csi-proxmox
    valuesFile: ./values.yaml
patches:
  - target:
      kind: CSIDriver
      name: csi.proxmox.sinextra.dev
    patch: |
      - op: replace
        path: /spec/storageCapacity
        value: false
