existingConfigSecret: proxmox-csi-plugin
existingConfigSecretKey: config.yaml
createNamespace: true

node:
  nodeSelector:
    node.cloudprovider.kubernetes.io/platform: nocloud
  tolerations:
    - key: node.cloudprovider.kubernetes.io/platform
      operator: Exists

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

storageClass:
  - name: proxmox-data-xfs
    storage: data
    reclaimPolicy: Delete
    fstype: xfs
  - name: proxmox-data
    storage: data
    reclaimPolicy: Delete
