apiVersion: v1
data:
  keys.txt: ENC[AES256_GCM,data:qJ6ZJTlz3oKZqNbeDAuIU24qb6aSgcyjOezbFSEsuZLO5q11KV/1PWYqVrAidXlcY8MewuHse1yde+85R41rj+TTeMXTrIfIC7XgSrCvbapEfMxJWsYf/PcZcnbMqswGExc/MmIw7Fg156T5ASLGI+seDGyiC+CXG/8rzeBG0Uk+rddF7u6InD7MoP3hMlXWAW9LBKVC5dMj++kQc2IhurVtfQC+PdvkT0JOmbhSujcoXxUyjTE4M0oujhlVrJUUYliy2RxOv9l5sBazOa7RgosvglY2xdeJcvN0cD4pHLTEI31+qq6OZE6Tisjo4O+nUTNHYsBm8V8vy2eA,iv:JfrNjZi54MLPqDxX4qYfivBAFhgbRmdDRHQuFdfy61s=,tag:3uW1N7XxlAVeKObi/USo1g==,type:str]
kind: Secret
metadata:
  name: sops-age
  namespace: openshift-operators
sops:
  age:
    - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2LzhIbFRHMVIwZ0xncThL
        L3hobmxBZUdSVmVjUURhYVpMWmVudEhtb2hvCi96VUJ0eTIyZjdqZXphZWhZY3Ru
        ck9tTlUrRWtWMzk0bm93ZnBzbGJFSjAKLS0tIENULzROZUE5bEE3WHM2dVNUSlRh
        bGN1ZHIrMWh6NlY3Skg5T2p6TnZaTzQKTZ5WB+KeZ9ORfWWltt2PJNTxoegJNMlT
        2g4hsNPyBri3MAvtIvjZ9pH0wo+RqmifDvHtRq88JLUEa0Zfgq7o7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T23:47:43Z"
  mac: ENC[AES256_GCM,data:8CXOl3WClWTlLkpeDJNCnPSlhBEHVHWap3+yvSKnuZHhx9L4HLFaHBTrWztR3tYBa7GyqfSv2rdGehg63JQjJt9s2sMevNaQv8Jmv+gpLWUtWhnLQkXlht/ez1HkQ/4Hufkh5EaLa8m6bsyxhdO6qCuHpfimOuVdnA690TFow5I=,iv:IDO8oyW8LCbcRsokszpTrZfMntJsW8zCOWZ3O5l9aMw=,tag:7Q/5ONLyt53VNRDzVuuH3w==,type:str]
  encrypted_regex: ^(keys.txt)$
  version: 3.11.0
