apiVersion: v1
data:
  keys.txt: ENC[AES256_GCM,data:8+mLk+kk1ghBGQIH955ORVFzcjtfipUxdfx8rF+0i6KjV5RIYvJJdxM8ZoR3K4DD1ttFRVn4qkyOiDIlH6UWO8ChuN6btex7t93WFSnxb/Pkz20/2gqWrKE92pFlr8lzPZ6Gr0gPfuGh1rbaKLrDaI91xPSpmNMGJLE9pKwacjSqCShEI6bCXOFSDLxh0/Qmd0i2lpacStxrc9yy/fckoowUBg+HusIgVtgGWHGf2aLFQ8sxMAlksG6rDyclgCGtGK0JQaPH8jiiiio6UGEZ1bS3kmLh/kdU2W7ra8f1lAv9hBbPA3iD5+bes7Y+lolHv8J1qk3CyUQQDxp9,iv:PwVwKEKrGMgtH6i6YqmY0PWLBfEKlrijyPlkzxmo6FQ=,tag:bvBpYpHWx23fDOLDyr5INQ==,type:str]
kind: Secret
metadata:
  name: sops-age
  namespace: argocd
sops:
  age:
    - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT29DZFhjRGF1eW5iVisv
        ODJ4cHVjMFFsTi9PdVZ0V08rcjdqeWpwREZjCmtLMHpKb3JTcFlHUkQ0bFpTSjMw
        M0ZYNTllSXhZdDdKQ1RNbldGWExmK1UKLS0tIEg0YmFZV0h3NXZ1NDdUSEQvaTcw
        TzFpNzhYclVoWUtCa1pxbTlqUlNUeTgKLaoLZC5vQu4CmXLLIonYK5Xv96NMiilN
        VE50wUM6DWPm4cQQkxTCgP6iXt/oDfKIGGCpj4fKHIWoDR+ArsWO0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:02:05Z"
  mac: ENC[AES256_GCM,data:qHksxhi5bu5sDY/JShXS0t6bV8knsWpwGqfXlpYZfCqKwQA+W62iJGSly2bmolaEGm/q7U1x5Edq+Z7p4Z51YD1Ad8jFvNCiS5ZVLXocjISXgJKCAzxxt+FMAOdvGrIWjk+mfhe6uL1KULZH/vnA5ae8aGBKuQlS76sYEaSYckc=,iv:8UA91Rs5NGklCBW399EWDUPoTxUqPv44HeVXSPk7lPM=,tag:Hz0hprY0L0rJzDi++nqDoQ==,type:str]
  encrypted_regex: ^(keys.txt)$
  version: 3.11.0
