# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-token-secret
#   namespace: cert-manager
# type: Opaque
# stringData:
#   api-token:
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCXJXiPp5T2S89GJ951cv694YFq4vruwy+Wm1R6arbAeoR2Zsujawslt3YQcypDY25TTtg8+T9o9PWU37s2v0uwQj09P3CybEAuwwUCzY76XfCDfR+PqZUQeSGEnu/BBjs93zz/WtefL5iaa489dJnupVwaQbNmqi+/+FjuuP/R+VS31ttcCOykw/5IYGpS2v1bZuRjsRgQFGC/PyHgJx1Ha/uhOecaOhXkcqmSSMiEq9PQruW3Xid+N/NR+jheFGrHs2BU4D5hUQy8bZk/HXXgK88MlC2lsbMr4OEjfY4r1LwCfZwn7YNihFhMZwTbpw9ce3mpTGCqZi5wxyi8K8la4tiixNm/itDl3wnzx52wNmsy+zeDi/KZm0VTANnTlhp1TjPSbbEP73AsKzSTuKDY9r1mZuANmXQbKdD68ODHHaWrrGJUseefDtNEYVPOk46KMC26X0cyzM95eKgiui8uLoZWQF4+wLO/OEQ4sni693fE8DE2TDBOyWWEWCmm+sF7Jx9IKcL2UYGouRxWKHKN4CCrl7Q79DlJu1jlO/8rcvkEoQ5K/bqizzCyE/ZJd1HTzbT/y1i2tb0oUnf4fJgwx23JCiL9PqdEiudoKo2gsWEeAR5YSHAfF9bVW2lcTXlKrOVuWTrGsGq1Vj3VwyfQURauM0w8CoRRZikuLdT7DzjrEw5qKtqiwR8IDMSeFUqIazqaAgUXQyU3fueM50Z1LFoOsaVLGSAQkoetUWrBso+1Hx3rvDWa
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
