apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-mp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: mc
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.23.2
    chart: minecraft
    helm:
      parameters:
        - name: minecraftServer.difficulty
          value: hard
        - name: minecraftServer.eula
          value: 'TRUE'
        - name: minecraftServer.hardcore
          value: 'false'
        - name: minecraftServer.loadBalancerIP
          value: 192.168.90.80
        - name: minecraftServer.memory
          value: 16384M
        - name: minecraftServer.servicePort
          value: '25566'
        - name: minecraftServer.serviceType
          value: LoadBalancer
        - name: minecraftServer.viewDistance
          value: '8'
        - name: minecraftServer.whitelist
          value: phonkd
        - name: resources.requests.memory
          value: 17000Mi
        - name: resources.requests.cpu
          value: 4000m
        - name: minecraftServer.version
          value: 1.21.3
        - name: persistence.storageClass
          value: 'longhorn'
        - name: persistence.dataDir.enabled
          value: 'true'
        - name: persistence.dataDir.size
          value: '20Gi'

  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true

