#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CLUSTER_DIR="$REPO_ROOT/modules/spawner/sel-001/clusters/clu01"
CILIUM_KUSTOMIZE_DIR="$CLUSTER_DIR/cilium"
CRS_OUTPUT="$CLUSTER_DIR/cilium-crs.yaml"
CONFIGMAP_OUTPUT="$CLUSTER_DIR/cilium-install.enc.yaml"

# Render Cilium manifests using kustomize with helm support
echo "🔨 Building Cilium manifests..."
CILIUM_MANIFESTS=$(kustomize build --enable-helm --load-restrictor LoadRestrictionsNone --enable-alpha-plugins --enable-exec "$CILIUM_KUSTOMIZE_DIR")

# Indent the manifests for embedding in ConfigMap (4 spaces)
INDENTED_MANIFESTS=$(echo "$CILIUM_MANIFESTS" | sed 's/^/    /')

# Generate the ClusterResourceSet YAML (unencrypted)
echo "📝 Generating ClusterResourceSet..."
cat > "$CRS_OUTPUT" << 'EOF'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: scripts/render-cilium-crs.sh
# Source: modules/spawner/sel-001/clusters/clu01/cilium/
#
# To regenerate: ./scripts/render-cilium-crs.sh

apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cilium-crs
  namespace: kube-system
spec:
  clusterSelector:
    matchLabels:
      cni: cilium
  resources:
    - kind: ConfigMap
      name: cilium-install
  strategy: Reconcile
EOF

# Generate the ConfigMap YAML (to be encrypted)
echo "📝 Generating ConfigMap..."
cat > "$CONFIGMAP_OUTPUT" << EOF
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: scripts/render-cilium-crs.sh
# Source: modules/spawner/sel-001/clusters/clu01/cilium/
#
# This file is encrypted with SOPS and decrypted by KSOPS on the cluster
# To regenerate: ./scripts/render-cilium-crs.sh
# To encrypt: sops -e -i $CONFIGMAP_OUTPUT

apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-install
  namespace: kube-system
data:
  cilium-manifests.yaml: |
$INDENTED_MANIFESTS
EOF

# Encrypt the ConfigMap with SOPS
echo "🔐 Encrypting ConfigMap with SOPS..."
if command -v sops &> /dev/null; then
    # Change to cluster directory so SOPS finds .sops.yaml
    cd "$CLUSTER_DIR"

    # Check if file is already encrypted
    if grep -q "sops:" "$(basename "$CONFIGMAP_OUTPUT")" 2>/dev/null; then
        echo "⚠️  File already encrypted, updating in place..."
        sops updatekeys -y "$(basename "$CONFIGMAP_OUTPUT")"
    else
        sops -e -i "$(basename "$CONFIGMAP_OUTPUT")"
    fi
    echo "✓ Encrypted $CONFIGMAP_OUTPUT"

    # Return to original directory
    cd "$REPO_ROOT"
else
    echo "⚠️  sops not found, ConfigMap not encrypted!"
    echo "   Install sops: https://github.com/getsops/sops"
fi

# Stage the files
git add "$CRS_OUTPUT" "$CONFIGMAP_OUTPUT" 2>/dev/null || true

echo ""
echo "✓ Generated files:"
echo "  - $CRS_OUTPUT"
echo "  - $CONFIGMAP_OUTPUT"
