#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CILIUM_KUSTOMIZE_DIR="$REPO_ROOT/modules/spawner/sel-001/clusters/clu01/cilium"
OUTPUT_FILE="$REPO_ROOT/modules/spawner/sel-001/clusters/clu01/AUTO-cni-crs.yaml"

# Render Cilium manifests using kustomize with helm support
CILIUM_MANIFESTS=$(kustomize build --enable-helm "$CILIUM_KUSTOMIZE_DIR")

# Indent the manifests for embedding in ConfigMap (4 spaces)
INDENTED_MANIFESTS=$(echo "$CILIUM_MANIFESTS" | sed 's/^/    /')

# Generate the ClusterResourceSet YAML
cat > "$OUTPUT_FILE" << EOF
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: scripts/render-cilium-crs.sh
# Source: modules/spawner/sel-001/clusters/clu01/cilium/
#
# To regenerate: ./scripts/render-cilium-crs.sh

# ClusterResourceSet to automatically install Cilium on child clusters
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cilium-crs
  namespace: kube-system
spec:
  clusterSelector:
    matchLabels:
      cni: cilium
  resources:
    - kind: ConfigMap
      name: cilium-install
  strategy: Reconcile
---
# ConfigMap containing rendered Cilium manifests
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-install
  namespace: kube-system
data:
  cilium-manifests.yaml: |
$INDENTED_MANIFESTS
EOF

git add "$OUTPUT_FILE"
echo "✓ Generated and staged $OUTPUT_FILE"
