#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CLUSTERS_DIR_DEFAULT="$REPO_ROOT/modules/spawner/sel-001/clusters"

CLUSTERS_DIR="${CLUSTERS_DIR:-$CLUSTERS_DIR_DEFAULT}"
TARGET_CLUSTER="${TARGET_CLUSTER:-}"
TARGET_ADDON="${TARGET_ADDON:-}"

CRS_NAMESPACE="${CRS_NAMESPACE:-kube-system}"
CRS_SELECTOR_KEY="${CRS_SELECTOR_KEY:-cni}"
CRS_SELECTOR_VALUE="${CRS_SELECTOR_VALUE:-cilium}"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/render-cilium-crs.sh [--clusters-dir PATH] [--cluster NAME] [--addon NAME]

Renders ClusterResourceSet + SOPS-encrypted ConfigMaps for every addon directory
under each cluster directory. An addon directory is any immediate child directory
of a cluster that contains a kustomization.yaml.

Env overrides:
  CLUSTERS_DIR, TARGET_CLUSTER, TARGET_ADDON
  CRS_NAMESPACE, CRS_SELECTOR_KEY, CRS_SELECTOR_VALUE
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --clusters-dir)
      CLUSTERS_DIR="$2"
      shift 2
      ;;
    --cluster)
      TARGET_CLUSTER="$2"
      shift 2
      ;;
    --addon)
      TARGET_ADDON="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

render_addon() {
  local cluster_dir="$1"
  local addon_dir="$2"
  local cluster_name addon_name
  cluster_name="$(basename "$cluster_dir")"
  addon_name="$(basename "$addon_dir")"

  local crs_output="$cluster_dir/${addon_name}-crs.yaml"
  local configmap_output="$cluster_dir/${addon_name}-install.enc.yaml"

  local tmp_manifests
  tmp_manifests="$(mktemp)"
  trap 'rm -f "$tmp_manifests"' RETURN

  echo "🔨 [$cluster_name] Building $addon_name manifests..."
  kustomize build \
    --enable-helm \
    --load-restrictor LoadRestrictionsNone \
    --enable-alpha-plugins \
    --enable-exec \
    "$addon_dir" > "$tmp_manifests"

  echo "📝 [$cluster_name] Generating $addon_name ClusterResourceSet..."
  cat > "$crs_output" <<EOF
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: scripts/render-cilium-crs.sh
# Source: ${addon_dir#"$REPO_ROOT"/}
#
# To regenerate: ./scripts/render-cilium-crs.sh

apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: ${addon_name}-crs
  namespace: ${CRS_NAMESPACE}
spec:
  clusterSelector:
    matchLabels:
      ${CRS_SELECTOR_KEY}: ${CRS_SELECTOR_VALUE}
  resources:
    - kind: ConfigMap
      name: ${addon_name}-install
  strategy: Reconcile
EOF

  echo "📝 [$cluster_name] Generating $addon_name ConfigMap..."
  {
    cat <<EOF
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: scripts/render-cilium-crs.sh
# Source: ${addon_dir#"$REPO_ROOT"/}
#
# This file is encrypted with SOPS and decrypted by KSOPS on the cluster
# To regenerate: ./scripts/render-cilium-crs.sh
# To encrypt: sops -e -i ${configmap_output#"$REPO_ROOT"/}

apiVersion: v1
kind: ConfigMap
metadata:
  name: ${addon_name}-install
  namespace: ${CRS_NAMESPACE}
data:
  ${addon_name}-manifests.yaml: |
EOF
    sed 's/^/    /' "$tmp_manifests"
  } > "$configmap_output"

  echo "🔐 [$cluster_name] Encrypting $addon_name ConfigMap with SOPS..."
  if command -v sops &> /dev/null; then
    if ! (cd "$cluster_dir" && sops -e -i "$(basename "$configmap_output")"); then
      echo "⚠️  [$cluster_name] SOPS encryption failed for $(basename "$configmap_output") (check ${cluster_dir#"$REPO_ROOT"/}/.sops.yaml)" >&2
    else
      echo "✓ [$cluster_name] Encrypted ${configmap_output#"$REPO_ROOT"/}"
    fi
  else
    echo "⚠️  sops not found, ConfigMap not encrypted!" >&2
  fi

  git add "$crs_output" "$configmap_output" 2>/dev/null || true

  echo "✓ [$cluster_name] Generated:"
  echo "  - ${crs_output#"$REPO_ROOT"/}"
  echo "  - ${configmap_output#"$REPO_ROOT"/}"
}

if [[ ! -d "$CLUSTERS_DIR" ]]; then
  echo "Clusters dir not found: $CLUSTERS_DIR" >&2
  exit 1
fi

clusters=()
if [[ -n "$TARGET_CLUSTER" ]]; then
  clusters+=("$CLUSTERS_DIR/$TARGET_CLUSTER")
else
  for d in "$CLUSTERS_DIR"/*; do
    clusters+=("$d")
  done
fi

did_any=false

for cluster_dir in "${clusters[@]}"; do
  [[ -d "$cluster_dir" ]] || continue

  addons=()
  for addon_dir in "$cluster_dir"/*; do
    [[ -d "$addon_dir" ]] || continue
    [[ -f "$addon_dir/kustomization.yaml" ]] || continue
    addon_name="$(basename "$addon_dir")"
    if [[ -n "$TARGET_ADDON" && "$addon_name" != "$TARGET_ADDON" ]]; then
      continue
    fi
    addons+=("$addon_dir")
  done

  if [[ ${#addons[@]} -eq 0 ]]; then
    continue
  fi

  for addon_dir in "${addons[@]}"; do
    did_any=true
    render_addon "$cluster_dir" "$addon_dir"
  done
done

if [[ "$did_any" != "true" ]]; then
  echo "No addon kustomizations found under: $CLUSTERS_DIR" >&2
fi
