apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: docmost
  name: docmost
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10000Mi
