apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-services-nix
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: k8s/clu-nix-k8s-1
    repoURL: https://github.com/phonkd/inventory.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "*"
      kind: "SealedSecret"
