apiVersion: v1
kind: Secret
metadata:
    name: capmox-manager-credentials-2
    namespace: capmox-system
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:nt9YHPTZRSYmzoCa56RTKKAR9gwpOV8fgzGOKhgBWYYb2Ydr,iv:CJxf0FvidNRou24gOYXXLNrX7ZR2fkK2XIcAybIE5R8=,tag:joNv60YjfUOKPzTci7hQQA==,type:str]
    url: https://oldblac.int.phonkd.net
    # The Proxmox VE TokenID for authentication
    token: capmox@pam!capi
    # The secret associated with the TokenID
    # generate using:
    # root@oldblac:~# pveum user token add root@pam capi --privsep=0
    # root@oldblac:~# pveum acl modify / --tokens 'root@pam!capi' --roles Administrator
sops:
    age:
        - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNDlWVEhBMFFiZkgvb3p1
            L1FXVUI0aldWT3V6eFhMUTZ4bTRvYkFhWXdZCmM2SjFrdnd4UFFtWDBaMjNaOGNa
            MngzM0t1Q1IydGw2WVdHRjVHYmVreVkKLS0tIGN6UVJCUmx2ZWRTQ24rUldsQkYw
            VllNRWp6a216RmErUU9ReVMwbnNhT3MK7x8ZzacbmCUk8KYi5/7Yyi6qZd8h4XHe
            Qgenq7xhqLCAcf6v/VrHt0iMn/6fDnHezS1PrsKwnsZnX1BuuW7YQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T20:35:01Z"
    mac: ENC[AES256_GCM,data:2YRPdAUTPrFg+no1AknwtwIQBe146PIZ3LDNGl3knXeTTtmd5atqHnhmtu4spYqsKg/41GEVqNY4Ay+z2OFv/bL+rvOwbvACfxHXLSefOHASCv0wgKnF2SDxqBYh0Bgt4QOPinPVlSScsPTOkcw0VNOlQOEjRzQTG0LdVAP+phw=,iv:PoyZe9GFUPwErGmBSdyapAwJ9A4qfftTwCTAoQiv4aI=,tag:wS9/bA+B3GpNTC/9x8a6yg==,type:str]
    encrypted_regex: ^(secret)$
    version: 3.11.0
