apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: beszel
spec: {}
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel-deployment
  namespace: beszel
  labels:
    app: beszel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beszel
  template:
    metadata:
      labels:
        app: beszel
    spec:
      containers:
      - name: beszel
        image: henrygd/beszel
        ports:
        - containerPort: 8090
        volumeMounts:
        - mountPath: /beszel_data
          name: beszel-data-volume
      restartPolicy: Always
      volumes:
      - name: beszel-data-volume
        persistentVolumeClaim:
          claimName: beszel-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: beszel-service
  namespace: beszel
spec:
  type: ClusterIP
  selector:
    app: beszel
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
