apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beszelundingressischdrgroeschtkak
  namespace: beszel
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
   # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - beszel.k8s.phonkd.net
    secretName: beszel-idkkk
  ingressClassName: nginx-ingress-int
  rules:
    - host: beszel.k8s.phonkd.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: beszel-service
              port:
                number: 8091