apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    name: beszel
    namespace: beszel
  spec:
    ingressClassName: nginx-ingress-int
    rules:
    - host: beszel.k8s.phonkd.net
      http:
        paths:
        - backend:
            service:
              name: beszel-service
              port:
                number: 8090
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - beszel.k8s.phonkd.net
      secretName: beszel-tls
kind: List
metadata:
  resourceVersion: ""
