keys:
  - &primary age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
creation_rules:
  - path_regex: authelia-secret\.yaml$
    key_groups:
      - age:
          - *primary

  - path_regex: secret\.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: secret\.txt$
    key_groups:
      - age:
          - *primary
